const AnagramActions = {
  ADDED_ANAGRAM: "ADDED_ANAGRAM",
  ADDING_ANAGRAM: "ADDING_ANAGRAM",
  FETCHED_ANAGRAMS: "FETCHED_ANAGRAMS",
  FETCHED_TOP_ANAGRAMS: "FETCHED_TOP_ANAGRAMS",
  SUBMITTING_ANAGRAM: "SUBMITTING_ANAGRAM",
  SUBMITTED_ANAGRAM: "SUBMITTED_ANAGRAM",
};

export default AnagramActions;
