version: "3.7"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.docker
    environment:
      - APP_ENV=production
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    environment:
      - APP_ENV=production
    depends_on:
      - db
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:
